DeveloperAcademy-POSTECH/MC2-Team3-SSAK3

- Taxi/Taxi/Component/RoundedButton.swift
> [Merge] HOTFIX!: Fix Color.brand to Color.customYellow

- Taxi/Taxi.xcodeproj/project.pbxproj
- Taxi/Taxi/Extension/ViewExtension.swift
- Taxi/Taxi/Presenter/SignUpView.swift
related to #17 
- underline이 들어간 textfield 작성
- underline을 만들어주는 함수는 view의 extension으로 작성
- textfield 코드 간결화를 위해 makeTextField function으로 분리
- button은 공통 component가 나오기 전까지 임시
- 올바른 code를 입력했는지 검사하는 로직 구현
- UserDefaults를 통해 회원가입 이미 한 유저인지 정보 저장
- private으로 선언한 makeTextField function의 구현방식이 옳은지 확인 부탁드립니다.
- 위의 makeTextField function에 optional한 function을 pass 하도록 구현하고 사용해봤는데 해당 부분이 올바르게 작성되었는지 확인 부탁드립니다
-  layout 위치 조정
- 및 #17 작업 리스트
- optional function은 어떻게 unwrapping해서 사용할까요?
- onAppear를 사용했을 때 focusState가 작동하지 않는 문제가 있어 asyncAfter로 시간차를 주었습니다. Help
- 레이아웃 구성하는 부분에서 항상 어려움이 있습니다. 내일 도움 주시길 바랍니다
optional function을 parameter로 넘기고 사용하는 방법
https://stackoverflow.com/questions/24395853/how-does-one-make-an-optional-closure-in-swift
focusState …
> [Merge] #17: Sign up

- Taxi/Taxi.xcodeproj/project.pbxproj
- Taxi/Taxi/Domain/UseCase/AuthenticateUseCase.swift
- Taxi/Taxi/Domain/UseCase/MyTaxiPartyUseCase.swift
- Taxi/Taxi/Extension/ColorExtension.swift
- Taxi/Taxi/Extension/TextStyleExtension.swift
- 택시팟 나가기, 참여한 택시팟 불러오기 함수를 정의한 유즈케이스 추가
- SwiftLint 워닝 해결
- [유즈케이스](https://github.com/DeveloperAcademy-POSTECH/MC2-Team3-SSAK3/compare/develop...DeveloperAcademy-POSTECH:feature%2F%2337_my_taxiparty_usecase?expand=1&title=37%20%5BFeature%5D%20My%20Taxi%20Party%20List%20유즈케이스%20추가#diff-7b2a3704fc9c3f9b32ce0fb746b4068155bb0b6df75500e406916e6dadcb62a6R10-R24)
- 택시팟 추가 화면 구현
> [Merge] #37: Add My TaxiParty UseCase

- Taxi/.swiftlint.yml
- Taxi/Taxi/Domain/Model/Place.swift
- 출발 장소 설정이 추가됨에 따라 적절한 출발 장소 추가 
- C5, 지곡회관, 택시 승강장, 카페베네 앞, 추후협의
- @pis3120 TaxiParty Cell View 에서 Place 를 활용해 출발, 도착장소를 보여줘야함
> [Merge] #42: Add departure place

- Taxi/Taxi.xcodeproj/project.pbxproj
- Taxi/Taxi/Domain/UseCase/AddTaxiParty.swift
- Taxi/Taxi/Domain/UseCase/AuthenticateUseCase.swift
- Taxi/Taxi/Domain/UseCase/GetTaxiParty.swift
- Taxi/Taxi/Domain/UseCase/JoinTaxiParty.swift
- Taxi/Taxi/Domain/UseCase/MyTaxiPartyUseCase.swift
- Taxi/TaxiTests/AddTaxiPartyUsecaseTest.swift
- 각 Usecase 에 completion closure 를 사용할 수 있는 API 추가
- 각 Usecase 에 추가된 API 들
- Combine 과 completion handler 중 원하는 API 를 사용하면 됩니다.
> [Merge] #69: Add completion closure API

- Taxi/Taxi.xcodeproj/project.pbxproj
- Taxi/Taxi/Presenter/AddTaxiParty/AddTaxiPartyView.swift
- Taxi/Taxi/Presenter/AddTaxiParty/InfoContainer.swift
- 질문, 유저 선택 정보, 토글 버튼 등을 표시하는 InfoContainer 구현
- [frame height 애니메이션](https://github.com/DeveloperAcademy-POSTECH/MC2-Team3-SSAK3/compare/develop...DeveloperAcademy-POSTECH:feature%2F%2327_add_taxi_party?expand=1&title=27%20%5BFeature%5D%20택시팟%20생성%20화면%20구현&body=%23%23%20작업사항%0A%0A%23%23%20리뷰포인트%0A%0A%23%23%23%20다음으로%20진행될%20작업%0A%0A%23%23%23%20질문%0A%0A%23%23%23%20기타%0A%0A%23%23%23%20References%0A#diff-9069347c0154326e3ef154e890e6ae0c5a39f4d1169405e23a42bb53b04e1295R24)
- [shadow 적용을 위한 zIndex 설정](https://github.com/DeveloperAcademy-POSTECH/MC2-Team3-SSAK3/compare/develop...DeveloperAcademy-POSTECH:feature%2F%2327_add_taxi_party?expand=1&title=27%20%5BFeature%5D%20택시팟%20생성%20화면%20구현&body=%23%23%20작업사항%0A%0A%23%23%20리뷰포인트%0A%0A%23%23%23%20다음으로%20진행될%20작업%0A%0A%23%23%23%20질문%0A%0A%23%23%23% …
> [Merge] #27: Add AddTaxiParty Info Container

- Taxi/Taxi/Assets.xcassets/customGreen.colorset/Contents.json
- Taxi/Taxi/Assets.xcassets/signUpYellowGray.colorset/Contents.json
- Taxi/Taxi/Extension/ColorExtension.swift
- Taxi/Taxi/Extension/TextStyleExtension.swift
색상 추가 및 글자 스타일 추가
#75 
색상 두가지와 텍스트 스타일 네가지 추가했습니다.
develop에 머지 해주시고 다른분들 반영하시면 됩니다.
> Feat: Color & text style

- Taxi/Taxi/Data/UserFirebaseDataSource.swift
- Taxi/Taxi/Domain/Interface/UserRepository.swift
- Taxi/Taxi/Domain/UseCase/AuthenticateUseCase.swift
- Taxi/TaxiTests/AuthenticateUsecaseTest.swift
- 프로필 이미지 삭제 유즈케이스 구현
- 프로필 이미지 삭제 테스트 추가
> [Merge] #80: Add Delete Profile Image

- Taxi/Taxi/Extension/TextStyleExtension.swift
calendar text style을 추가했습니다
merge 후 calendar hifi branch를 develop rebase 해야합니다
> Feat: Add calendar textstyle

- Taxi/Taxi.xcodeproj/project.pbxproj
- Taxi/Taxi/Extension/DateExtension.swift
- Taxi/Taxi/Extension/TextStyleExtension.swift
- Taxi/Taxi/Presenter/AddTaxiParty/AddTaxiParty.swift
- AddTaxiParty UI 구현
https://user-images.githubusercontent.com/57793298/173544454-de8b9091-d163-42ac-a881-c187ae0f10ff.mp4
- [stroke 두께를 일정히 주기 위해 offset 을 조정함](https://github.com/DeveloperAcademy-POSTECH/MC2-Team3-SSAK3/compare/develop...DeveloperAcademy-POSTECH:feature%2F%2327_add_taxi_party_ui?expand=1&title=27%20%5BFeature%5D%20택시팟%20생성%20화면%20구현#diff-ca6e65972b124f8cea2e4f909e0392fc8c3d79d83955db07e8acaa47ecb9d711R48-R55)
- [동일하게 나타나는 Rounded Background 를 Modifier 화](https://github.com/DeveloperAcademy-POSTECH/MC2-Team3-SSAK3/compare/develop...DeveloperAcademy-POSTECH:feature%2F%2327_add_taxi_party_ui?expand=1&title=27%20%5BFeature%5D%20택시팟%20생성%20화면%20구현#diff-ca6e65972b124f8cea2e4f909e0392fc8c3d79d83955db07e8acaa47ecb9d711R269-R287)
> [Merge] #27: Add AddTaxiParty UI

- Taxi/Taxi.xcodeproj/project.pbxproj
- Taxi/Taxi/Presenter/AddTaxiParty/AddTaxiParty.swift
- Taxi/Taxi/Presenter/ViewModel/AddTaxiPartyViewModel.swift
- AddTaxiParty 기능을 구현하는 AddTaxiPartyViewModel 추가
- AddTaxiParty 버튼에 해당 기능 연결
- [AddTaxiPartyViewModel 과 @StateObject 로 View 와 ViewModel 을 바인딩 하는 코드](https://github.com/DeveloperAcademy-POSTECH/MC2-Team3-SSAK3/compare/develop...DeveloperAcademy-POSTECH:feature%2F%2327_add_taxi_party_use_case?expand=1&title=27%20%5BFeature%5D%20택시팟%20생성%20화면%20구현&body=%23%23%20작업사항%0A%0A%23%23%20리뷰포인트%0A%0A%23%23%23%20다음으로%20진행될%20작업%0A%0A%23%23%23%20질문%0A%0A%23%23%23%20기타%0A%0A%23%23%23%20References%0A#diff-ca6e65972b124f8cea2e4f909e0392fc8c3d79d83955db07e8acaa47ecb9d711R30)
- 추후 코드 리팩토링 작업 예정
- 채팅방 이동 기능 구현 예정
> [Merge] #27: Add TaxiParty ViewModel to use usecase

- Taxi/Taxi/TaxiApp.swift
최상단인 @main에 유저 환경객체를 추가했습니다.
- 최상단에 StateObject로 인스턴스 생성
- RootView에 environmentObject로 전달하여 어플의 모든 뷰에서 접근 가능하도록 설정
- StateObject를 쓰는게 맞을까요?
- userViewModel 이름이 뭔가 맘에 안들어요
> [Merge] #97 최상단에 User 환경객체 추가

- Taxi/Taxi.xcodeproj/project.pbxproj
- Taxi/Taxi/Data/ChattingFirebaseDataSource.swift
- Taxi/Taxi/Domain/Interface/ChattingRepository.swift
- Taxi/Taxi/Domain/Model/Message.swift
- Taxi/Taxi/Domain/UseCase/ChattingUseCase.swift
- Taxi/TaxiTests/ChattingUseCaseTest.swift
- Chatting Repository 프로토콜 정의
- 메시지 전송 기능 구현
- 메시지 전송 기능 테스트 추가 & 확인
- completion handler 와 Combine API 제공
- 채팅 메시지를 관리할 ObservableObject 생성
> [Merge] #13: Add Chatting Data Layer

- Taxi/Taxi.xcodeproj/project.pbxproj
- Taxi/Taxi/Domain/Model/Message.swift
- Taxi/Taxi/Extension/DateExtension.swift
- Taxi/Taxi/Presenter/ViewModel/ChattingViewModel.swift
- 메시지 전송
- 실시간 메시지 수신 등의 기능을 담은 Chatting Observable Object 구현
- [실시간 메시지 변경 이벤트 수신 리스너 등록](https://github.com/DeveloperAcademy-POSTECH/MC2-Team3-SSAK3/compare/develop...DeveloperAcademy-POSTECH:feature%2F%23100_chatting_observable_object?expand=1&title=Feat%3A%20Add%20ChattingViewModel#diff-9a41c540d3b532bd6ad6f7d8529bfdbabf6ddf34e664813d597f8c6d47eda212R29-R46)
- [실시간 메시지 변경 이벤트 수신 리스너 해제](https://github.com/DeveloperAcademy-POSTECH/MC2-Team3-SSAK3/compare/develop...DeveloperAcademy-POSTECH:feature%2F%23100_chatting_observable_object?expand=1&title=Feat%3A%20Add%20ChattingViewModel#diff-9a41c540d3b532bd6ad6f7d8529bfdbabf6ddf34e664813d597f8c6d47eda212R48-R50)
- ChattingViewModel 은 TaxiParty 를 넘겨줘야 생성할 수 있다. (TaxiParty 의 subcollection 으로 message 들이 쌓이는 형식)
- 실시간 스냅샷 리스너는 항상 채팅방 화면이 아닐 때 …
> [Merge] #100: Add ChattingViewModel Observable Object

- Taxi/Taxi/Presenter/CalendarModal.swift
- Taxi/Taxi/Presenter/PatyListCell.swift
- Taxi/Taxi/Presenter/TaxiPartyListView.swift
1. PatyListCell 파일 내 IF문 사용
2. func meetTimeSeparator내 IF문 사용
UI는 끝났으니, PatyListView에서 실제 Data 바인딩 필요
> Feature/#93 PatyListCell_UI 디자인 픽스된 것 구현 

- Taxi/Taxi/Presenter/ViewModel/JoinTaxiPartyViewModel.swift
- 택시팟 참가에 사용될 JoinTaxiPartyViewModel을 추가함
- joinTaxiParty는 왜 TaxiParty를 반환하죠??
- 정보 확인 페이지에서 시작하기 버튼을 누르면 택시팟에 참여되도록
> [Merge] #118 JoinTaxiPartyViewModel 추가

- Taxi/Taxi.xcodeproj/project.pbxproj
- Taxi/Taxi/Domain/Model/Place.swift
- Taxi/Taxi/Presenter/PatyListCell.swift
- Taxi/Taxi/Presenter/TaxiPartyListView.swift
- Taxi/Taxi/Presenter/ViewModel/TaxiPartyListViewModel.swift
TaxiPartyList 데이터 바인딩
1. TaxiPartyListViewModel 내, taxiPartyListUseCase.getTaxiParty(exclude: nil, force: true) 구문
2. PatyListCell 파일 내, party.destinationCode == 0 기준으로 작성한 if-else 구문 및 private func 
3. PatyListCell의 시간구분자 ":" 표시 방법
> Feat: #117 taxi party list data binding

- Taxi/Taxi/Assets.xcassets/AccentColor.colorset/Contents.json
- Taxi/Taxi/Component/ProfileImage.swift
- Taxi/Taxi/Extension/ImageExtension.swift
- Taxi/Taxi/Presenter/MyPageView.swift
- Taxi/Taxi/Presenter/ProfileView.swift
- 설정 탭 하이파이 적용
- 프로필 관리 화면 하이파이 적용
- 설정 탭의 구분선 색상이 에셋에 없고, 여기서만 쓰이는 색상이라 RGB 값으로 넣어줬습니다.
- 프로필 관리 화면에서 특수문자 입력 방지하기
> [Merge] #114 설정 탭에 하이파이 적용

- Taxi/Taxi/Extension/StringExtension.swift
- Taxi/Taxi/Presenter/ProfileView.swift
- Taxi/Taxi/Presenter/TaxiPartyInfoView.swift
- 닉네임에 특수문자 입력시 적용 버튼 비활성화
- 정보 확인 뷰에 요일까지 표시
- 정보 확인 뷰의 프사와 닉네임 사이 간격 조정
- 화면을 연결해야 할 수 있는 정보 확인 뷰의 남은 TODO들 제거
> [Merge] #138 남은 TODO들 제거

- Taxi/Taxi/Presenter/ChatRoomView.swift
- Taxi/Taxi/Presenter/ViewModel/ChattingViewModel.swift
- 채팅방 UI 리팩토링
- 채팅 메시지 업데이트 시 제일 하단으로 스크롤 구현
- authentication 대신 userProfileViewModel 사용
> Feat: Add Scroll View Reader

- Taxi/Taxi/Data/TaxiPartyFirebaseDataSource.swift
- Taxi/Taxi/Domain/Interface/TaxiPartyRepository.swift
- Taxi/Taxi/Domain/UseCase/AddTaxiPartyUseCase.swift
- Taxi/Taxi/Presenter/AddTaxiParty/AddTaxiParty.swift
- Taxi/Taxi/Presenter/ChatRoomView.swift
- Taxi/Taxi/Presenter/MyParty/MyPartyView.swift
- Taxi/Taxi/Presenter/TaxiPartyTab/TaxiPartyListView.swift
- Taxi/Taxi/Presenter/ViewModel/AddTaxiPartyViewModel.swift
- Taxi/Taxi/Presenter/ViewModel/ChattingViewModel.swift
- 택시팟 생성 버튼 클릭 시 loading state 활성화하여 유저가 여러 번 버튼을 클릭하는걸 방지하였다.
- viewModel 에서 loading State 의 표현 방법
- [loading state 의 변경 시점](https://github.com/DeveloperAcademy-POSTECH/MC2-Team3-SSAK3/compare/develop...DeveloperAcademy-POSTECH:feature%2Fadd_loding_state_to_add_taxi_party?expand=1&title=Feat%3A%20Add%20Loading%20state%20to%20Add%20Taxi%20Party%20View#diff-98fd0c9ffb03357d3f3e21b5982865c16fb8ec1d727327114cf6e96c1b1b9a17R22-R27)
> [Merge]:  Add Loading state to Add Taxi Party View

- Taxi/Taxi.xcodeproj/project.pbxproj
- Taxi/Taxi/Data/TaxiPartyFirebaseDataSource.swift
- Taxi/Taxi/Data/UserFirebaseDataSource.swift
- Taxi/Taxi/Domain/Model/FirebaseError.swift
- Taxi/Taxi/Presenter/ChatRoomView.swift
- Taxi/Taxi/Presenter/MainView.swift
- Taxi/Taxi/Presenter/TaxiPartyTab/TaxiPartyListView.swift
- Taxi/Taxi/Presenter/ViewModel/Authentication.swift
- 채팅방 빈 영역 터치 시 키보드 숨김 기능 구현
- join Taxi Party 로직 리팩토링
- 최초 로그인 시 강제로 유저를 불러오도록 수정
- [@FocusState 를 활용한 키보드 숨김 기능](https://github.com/DeveloperAcademy-POSTECH/MC2-Team3-SSAK3/compare/develop...DeveloperAcademy-POSTECH:feature%2Fhide_keyboard?expand=1&title=Feat%3A%20Add%20hide%20keyboard%20in%20chattingRoom#diff-775e58c25932eeb4d21481ce5b589549dfe30526c1bdb8b079bc69e281b722b6R10-R30)
> [Merge] Add hide keyboard in chattingRoom & Refactoring code

- Taxi/Taxi/Presenter/Component/RoundedButton.swift
- Rounded Button 의 tap 영역이 label 전체를 차지하도록 수정
> [Merge]: Fix Rounded Button Content shape

- Taxi/Taxi/Presenter/Component/CalendarHelper.swift
- Taxi/Taxi/Presenter/Component/CalendarView.swift
- Taxi/Taxi/Presenter/TaxiPartyTab/CalendarModal.swift
lazyVGrid로 인해 생기는 애니메이션 이슈를 해결하기 위해 VStack과 HStack의 결합 구조로 변경하였습니다.
시연 영상에서 처음에 나타나는 버벅임은 업로드 과정에서 생긴 문제로 실제 구동시 발생하지 않는 문제입니다.
> Refactor: change calendar lazyVGrid to VStack and Hstack

- Taxi/Taxi.xcodeproj/project.pbxproj
- Taxi/Taxi/Data/UserFirebaseDataSource.swift
- Taxi/Taxi/Domain/Interface/UserRepository.swift
- Taxi/Taxi/Domain/UseCase/SendEmailUseCase.swift
- Taxi/TaxiTests/SendEmailUseCaseTest.swift
- 인증을 위한 이메일 전송 기능 구현
- 이메일 전송 테스트 추가
> [Merge]: Add Send Email Feature

- Taxi/Taxi/Presenter/Component/UnderlinedTextField.swift
- 접미 문장을 표시하기 위해 postFixText 프로퍼티를 추가 
- 접미 문장을 표현하기 위해 UI 요소 변경
> [Merge]: Fix Underlined Text Field

- Taxi/Taxi.xcodeproj/project.pbxproj
- Taxi/Taxi/Constant/ImageName.swift
- Taxi/Taxi/Presenter/SignIn/SignIn.swift
- Taxi/Taxi/Presenter/System/AppState.swift
- Taxi/Taxi/Presenter/System/RootView.swift
- Taxi/Taxi/Presenter/System/Splash.swift
| 작업 전 | 작업 후 |
|:---:|:---:|
|<img width="250" src="https://user-images.githubusercontent.com/75792767/186140687-4608a431-38f2-4649-aea6-1dddc431489a.gif">|<img width="250" src="https://user-images.githubusercontent.com/75792767/186140670-7a5e0f71-3f7a-4d10-bccb-d6613d41e689.gif">|
- 어플 실행시 자동 로그인이 되는 동안 온보딩 화면이 보여지는 것을 수정했습니다.
- 추후 스플래시 화면이 변경될 수도 있다고 생각하여 LaunchScreen 스토리보드를 사용하지 않고 `Splash` 뷰를 따로 만들었습니다.
- `LoginState` enum으로 앱에 무슨 화면이 띄워질지를 관리합니다.
UserDefaults에 이메일과 패스워드가 저장되어 있지 않을 때는 loginState가 .none이고, 온보딩 화면을 표시합니다.
UserDefaults에 이메일과 패스워드가 저장되어 있어 자동 로그인이 진행중일 떄는 loginState가 .loading이고, Splash 화면을 표시합니다.
자동 로그인이 완료되어 AppState.currentUserInfo가 nil이 아니면 loginState가 .succeed고, MainView를 표시합니다.
- 원래 MainView의 상태 관리를 담당하던 AppState.currentUserInfo가 LoginState Enum에 통합되어 삭제됐습니다.
- …
> [Feature] Fix Autologin & Add Splash

- Taxi/Taxi.xcodeproj/project.pbxproj
- Taxi/Taxi/Domain/Model/TaxiParty.swift
- Taxi/Taxi/Extension/ColorExtension.swift
- Taxi/Taxi/Presenter/Chatting/ChatRoomInfo.swift
- Taxi/Taxi/Presenter/Chatting/ChatRoomView.swift
- Taxi/Taxi/Presenter/Chatting/ChattingViewModel.swift
- Taxi/Taxi/Presenter/TaxiPartyInfo/TaxiPartyInfo.swift
- Taxi/Taxi/Resources/Assets.xcassets/deepGray.colorset/Contents.json
1. 채팅방 우측 상단에 검정색 Person 아이콘 클릭 
2. 디자이너 요청으로, 나가기 버튼과 Person아이콘을 Hstack으로 묶어서 배치
3. 해당 채팅방 상세정보 보기 가능
4. "모집 완료" or "모집 중" 표시, 삼항연산자 사용
5. 디자인 요건 충족
6. 스와이프로 화면 닫기
> [Feature] ChatRoomInfo 화면 추가

- Taxi/Taxi/Presenter/MyPage/MyPageView.swift
- Taxi/Taxi/Presenter/MyParty/MyPartyView.swift
- Taxi/Taxi/Presenter/TaxiPartyInfo/TaxiPartyInfo.swift
- Taxi/Taxi/Presenter/TaxiPartyList/TaxiPartyList.swift
- 택시팟 참가시 블러 안 없어지는 버그 제거
- 택시팟 정보뷰 불러올 때 블러 애니메이션 다시 되돌림
- 택시팟 참가하자마자 채팅방이 열렸을 때, 나가기 누르면 튕기는 버그 수정
- 설정 탭에 내비게이션 스타일이 적용이 안 되어 있어서 로그아웃 후 바로 다시 로그인하면 화면이 이상해지는 버그 수정
- 택시팟 참가시 정보뷰가 닫히지 않는 버그 수정
> [Bug] 남아있는 버그들 제거

- Taxi/Taxi/Presenter/System/AppState.swift
- Taxi/Taxi/System/TaxiApp.swift
- Amplitude 연동 및 로그인 로그 이벤트 등록 테스트 확인!
> [Merge] #259 Feat: Add Amplitude

- Taxi/Taxi.xcodeproj/project.pbxproj
- Taxi/Taxi/Domain/Interface/AuthenticateAdapter.swift
- Taxi/Taxi/Domain/Service/FirebaseAuthenticatorAdapter.swift
- Taxi/Taxi/Domain/UseCase/ResetPasswordUseCase.swift
- Taxi/Taxi/Presenter/SignIn/ResetPassword.swift
- Taxi/Taxi/Presenter/SignIn/ResetPasswordViewModel.swift
- Taxi/Taxi/Presenter/SignIn/SignIn.swift
- 로그인 페이지에 비밀번호 재설정 링크 추가
- 비밀번호 재설정 페이지에서 이메일 입력받고 비밀번호 재설정 메일 전송 
- 비밀번호 메일 보내는 함수 추가
- 비밀번호 재설정 보내는 함수 관련해서 추가한 부분 확인 부탁드립니다.
> [Feature] 비밀번호 재설정

- Taxi/Taxi/Data/Repository/TaxiPartyFirebaseDataSource.swift
- Taxi/Taxi/Domain/Model/TaxiParty.swift
- Taxi/Taxi/Presenter/TaxiPartyInfo/TaxiPartyInfo.swift
- 모임 시간이 지나갔음에도 로딩되던 버그 해결!!
- 정원이 다 찬 택시팟도 보이도록 수정
- 정원이 다 찬 택시팟은 참가버튼이 비활성화되도록 수정!
- 원래는 정원이 다 찬 택시팟이 보이지 않았는데, 이제 보이도록 수정했습니다. 
- 정원이 다 찼을 때 택시팟 참가 버튼이 비활성화되는게 정상이기 때문에 그렇게 수정했습니다
- 날짜, 시간 필터링은 모두 Data Layer 에서 진행됩니다.
> Bug: Fix #263 and some bugs

- Taxi/Taxi.xcodeproj/project.pbxproj
- Taxi/Taxi/Presenter/MyPage/EmailSendView.swift
- Taxi/Taxi/Presenter/MyPage/LicenseView.swift
- Taxi/Taxi/Presenter/MyPage/MyPageView.swift
-설정화면에서 "개발자에게 의견 남기기" 버튼 누르면 이메일 폼으로 넘어감
- 이메일 앱 미설치시, 앱스토어로 연결 
- 설정화면에서 "오픈소스 라이선스"누르면 오픈소스 라이선스 볼 수 있음 
- 시뮬레이터에서는 앱스토어로 연결되는 것이 작동하지 않으므로
- 실기기에 디버깅해서 확인할 것!
https://user-images.githubusercontent.com/40324511/198861044-546425a3-84d9-4d22-af75-9ad8b436cd9e.mp4
https://user-images.githubusercontent.com/40324511/198861048-15b37915-d62b-4fb7-a9f5-11fbe6c56a35.mp4
> [Feature] #270 설정 화면의 "개발자에게 의견 남기기" & "오픈 라이선스" 구현
