DeveloperAcademy-POSTECH/MC2-Team3-SSAK3

Taxi/Taxi.xcodeproj/project.pbxproj
Taxi/Taxi/Extension/ImageExtension.swift
Taxi/Taxi/Presenter/PhotoPicker.swift
Taxi/Taxi/Presenter/ProfileView.swift

- 더미데이터를 기반으로 유저가 닉네임과 프로필 사진을 변경할 수 있도록 구현
- PHPicker 추가
- SDWebImageSwiftUI 패키지 추가
|Placeholder|ActionSheet|PHPicker|
|:---:|:---:|:---:|
|![Placeholder](https://user-images.githubusercontent.com/75792767/173177476-9127c884-b8fe-4467-9955-6fb8770e52e4.png)|![ActionSheet](https://user-images.githubusercontent.com/75792767/173177485-534e1f20-f0ca-40e5-8ac2-235d62305e1f.png)|![PHPicker](https://user-images.githubusercontent.com/75792767/173177491-e3ac6729-f56e-491d-a88c-c71c2f96a782.png)|
|프로필 사진이 없을 때|프로필 사진이 있을 때|프로필 사진 변경|
|:---:|:---:|:---:|
|![DeleteImage](https://user-images.githubusercontent.com/75792767/173177540-9f720c8f-dc54-43f4-93de-f4f9645dfe19.png)|![ProfileImage](https://user-images.githubusercontent.com/75792767/173177524-b306ae6d-efc1-4c04-9b91-241c8e07303b.png)|![ChangeIma …

[Merge] #40: User Profile Change (with mockData)

---

Taxi/Taxi.xcodeproj/project.pbxproj
Taxi/Taxi/Presenter/TaxiPartyInfoView.swift

- 택시팟 참여 전 정보확인 뷰의 로파이 디자인 구현
- TaxiParty 더미데이터 추가
- 더미데이터로 택시팟 정보 표시
- 아직 디자인 픽스가 되지 않았지만 현재 디자인대로면 모달의 배경이 유리재질 느낌이어야 되는데, 이러면 커스텀 모달로 구현해야 하는건지? (UIKit을 적용하여 모달의 배경을 유리 재질로 만드는것 까지는 해봤는데, 뒷배경(모달이 나오기 전 화면)이 줄어드는 애니메이션을 끄는 방법은 모르겠음)
- TaxiParty 모델의 변화가 예상되어 TaxiParty 더미데이터는 생성하지 않음

[Merge] #49 TaxiPartyInfoView Lofi

---

Taxi/Taxi.xcodeproj/project.pbxproj
Taxi/Taxi/Component/ProfileImage.swift

```swift
ProfileImage(User(id: "1", nickname: "아보", profileImage: nil), diameter: 100)
```
매개변수로 User 타입과 프로필 사이즈를 주면 됨
- User와 프로필 사진 크기를 매개변수로 받음
- User.profileImage가 nil이면 텍스트를, 주소가 있으면 사진을 불러옴
- 텍스트 크기는 프로필 크기에 따라 변하도록 만듦
- 기본 프로필의 색상 변경
- 기본 프로필의 텍스트 폰트 변경

[Merge] #56: Add ProfileImage Component

---

Taxi/Taxi/Constant/ImageName.swift
Taxi/Taxi/Presenter/TaxiPartyInfoView.swift

TaxiPartyInfoView에서 하드코딩 했던 부분에 더미데이터를 적용
- ForEach를 사용하여 참여해있는 택시팟 멤버 정보와 빈자리 표현
- switch문으로 도착지에 따라 출발지에 '포스텍'이나 '포항역' 표시
- Assets에 택시 아이콘과 기차 아이콘 추가, ImageName.swift에 아이콘 이름 추가
- 유즈케이스를 활용하여 실제 데이터와 연결
- 앞으로 뷰에 택시 아이콘과 기차 아이콘을 사용할 때는 제가 이번에 추가한 에셋을 활용해주세요~ 둘 다 크기가 똑같아서 레이아웃 짜기 수월해질 것입니다!
- 디자인 시안에서는 '몇월 며칠' 옆에 요일도 표시되는데, 이건 어떻게 하는 것인지
- #24 에서 택시팟 날짜 표현 방식을 가져왔습니다~ @YoonyoungL 에게 감사드립니다~

[Merge] #52 TaxiPartyInfoView에 더미데이터 적용

---

Taxi/Taxi/Presenter/ViewModel/Authentication.swift

Authentication 뷰모델에 유저의 프로필을 삭제하는 메서드 추가
- deleteProfileImage 유즈케이스 사용
- TaxiApp.swift에 environmentObject 수식어로 뷰모델 전달하여 모든 뷰에서 사용 가능하도록 설정

[Merge] #89 Add deleteProfileImage Method in Authentication

---

Taxi/Taxi/Presenter/ChatRoomView.swift

- 채팅 (내 채팅, 상대 채팅, 입장 채팅) UI 구현
- 최대 3줄까지 늘어나는 채팅 입력 영역 구현
https://user-images.githubusercontent.com/58019653/173822662-be225768-9dd0-40e8-abdd-f338698beb76.mp4
- 채팅 입력 영역 실제 기기로 확인 부탁드립니다
[특정 코너만 둥글게 만들기](https://stackoverflow.com/questions/56760335/round-specific-corners-swiftui)
[텍스트에디터 높이 조절](https://stackoverflow.com/questions/69002861/controlling-size-of-texteditor-in-swiftui)

Feat: Add Chat Bubble and Typing Area

---

Taxi/Taxi/Extension/DateExtension.swift
Taxi/Taxi/Presenter/CalendarView.swift

오늘 날짜 기본으로 selected 되지 않도록
month type 제거
모달에서는 bool 값을 활용하여 modal의 확인 버튼 활성화 및 토스트 메시지 생성, selectedDate 값 넘겨주어 scrolling 하는 작업을 하면 됩니다.
```swift
CalendarView {bool, date in
if bool {
print("there is taxiParty \(date)")
// 모달 확인 버튼 활성화
} else {
print("there isn't taxiParty \(date)")
// 토스트 메시지 생성, 모달 확인 버튼 비활성화
}
}
```
scroll 하여 알맞은 태그 위치로 가기 위해서 Date형식의 값을 Int(yyyyMMdd) 형식으로 바꿔줘야하는데  DateExtension 파일에 있는 아래 함수를 사용하면 됩니다
```swift
// DateExtension.swift
var formattedInt: Int? {
let formattedStr = self.intFormatter.string(from: self)
return Int(formattedStr)
}
// 사용법
selectedDate.formattedInt
```
파티 생성에서는 bool 값을 _로 받아와서 신경 쓰지 않고 작업하시면 됩니다.
```swift
CalendarView {_, date in
print("make party in \(date)")
}
```

Feat: 캘린더 변경사항 적용

---

Taxi/Taxi.xcodeproj/project.pbxproj
Taxi/Taxi/Presenter/ViewModel/UserProfileViewModel.swift

- TaxiParty.members에 담긴 [id] 배열로 부터 User 정보를 얻을 수 있는 뷰모델 추가
- 택시팟 멤버 중 특정 멤버의 정보만을 가져올 수 있도록 [id: User]의 딕셔너리로 멤버 정보를 저장
1. 뷰가 불러와 질 때 TaxiParty.members 배열을 넣어서 유저 정보를 불러옴
```swift
@StateObject private var userProfileViewModel = UserProfileViewModel()
var body: some View {
...
.onAppear {
userProfileViewModel.getMembersInfo(taxiParty.members)
}
}
```
2. 특정 id의 User 정보만 가져올 수 있음
```swift
if let user = userProfileViewModel.membersInfo[memberID] { // user에 id로 memberID를 갖는 User 정보가 담김!!
ProfileImage(user, diameter: 80) // 프로필 이미지에 사용 가능
}
```

[Merge] #112 택시팟 멤버의 User 정보를 가져오는 UserProfileViewModel 추가

---

Taxi/Taxi/Presenter/CalendarModal.swift

#111 
캘린더 모달에 달력을 연결
택시팟이 없을 경우 토스트 메세지 생성
modal에 scroll view proxy를 받아와서 scrollTo 함수 사용을 통해 날짜 찾기 기능 구현
달력이 LazyVGrid로 만들어지다 보니 animation에서 어색한 점이 있다. 
그래서 현재 모달 transition을 없앤 상태이고, 해당 사항에 대한 방안으로 vgrid를 tabview나 scrollview로 감싸는 방법이 있다.
이 방법들은 너무 맞지 않는 것 같아 새로운 방안을 생각해보려 한다.

Feat: calendar modal 로직 구현

---

Taxi/Taxi/Presenter/CalendarModal.swift
Taxi/Taxi/Presenter/TaxiPartyListView.swift

택시파티뷰에서 날짜선택 버튼 클릭 후, 달력 날짜로 채팅방 필터링 구현
CalendarModal에서 storeDate 변수를 활용하여, selectedDate값을 storeDate에 넣고
storeDate 값을 "확인"버튼이 눌렸을때, renderedDate에 넣어주어 TaxiPartyListView로 전달

Feature/#124 Half-Modal에서 Calender Date Filtering 구현

---

Taxi/Taxi.xcodeproj/project.pbxproj
Taxi/Taxi/Presenter/TaxiPartyInfoView.swift
Taxi/Taxi/Presenter/ViewModel/JoinTaxiPartyViewModel.swift
Taxi/Taxi/Presenter/ViewModel/UserProfileViewModel.swift

- 정보 확인 페이지에서 택시팟 멤버의 프로필 사진과 이름 표시
- 시작하기 버튼 누르면 택시팟에 참가됨
- userProfileViewModel의 membersInfo 딕셔너리가 초기에 빈 값이라, 데이터가 로딩이 다 안됐을 때를 상정한 플레이스홀더를 만들었습니다.
- userViewModel의 옵셔널 체크를 if let으로 했는데, 이 방식이 맞을까요?
- 시작하기 버튼 누르면 채팅방으로 이동하도록
- 요일 추가

[Merge] #67 정보 확인 페이지에 뷰모델 연동

---

Taxi/Taxi.xcodeproj/project.pbxproj
Taxi/Taxi/Assets.xcassets/clearYellow.colorset/Contents.json
Taxi/Taxi/Extension/ColorExtension.swift
Taxi/Taxi/Extension/DateExtension.swift
Taxi/Taxi/MockData/MessageMockData.swift
Taxi/Taxi/Presenter/ChatRoomView.swift
Taxi/Taxi/Presenter/ViewModel/ChattingViewModel.swift

- 내 메시지 UI 추가
- 상대방 메시지 UI 추가
- ChattingViewModel 과 연결
- 메시지 List 추가
- Message Mockdata 추가
- 내 메시지 UI
- 상대방 메시지 UI
- 메시지 List
- dateFormatter 를 static 으로 변경 -> dateFormatter 는 애플리케이션 전반적으로 정말 많은 곳에서 사용되고, 또한 불변하니 static 으로 사용 가능 -> 결론적으로 생성 비용을 아낄 수 있다.
- 현재는 Authentication 모델을 사용해 각 메시지 별 유저를 불러오는데, 유저만 불러오는 뷰모델을 생성해서 갈아끼우기

[Merge] #107: Add Chatting room UI

---

Taxi/Taxi/Extension/DateExtension.swift

날짜와 요일을 나타내는 formatter 생성
weekday index를 요일로 바꾸는 작업에서 switch문을 사용했는데 좀 더 깔끔한 방법이 없을까요
```swift
static func convertToKoreanDateFormat(from date: Int) -> String {
guard let date = self.convertToDateFormat(from: date), let month = date.month, let day = date.day else { return "" }
return "\(month)월 \(day)일 \(date.weekday)"
}
```
```swift
Date.convertToKoreanDateFormat(from: 20220616)
// return 값 6월 16일 목요일
```

Feat: date, day formatter 생성

---

Taxi/Taxi/Presenter/CalendarModal.swift
Taxi/Taxi/Presenter/TaxiPartyListView.swift
Taxi/Taxi/TaxiApp.swift

택시파티 리스트의 목적지 필터링 처리 
1. 택시파티리스트뷰에서 CellViewList내 데이터 불러오는 것, function 처리
2. 택시파티리스트뷰에서 메인뷰내 filterCalender()으로 function처리

Feature/#133 Taxi party list destination filtering

---

Taxi/Taxi.xcodeproj/project.pbxproj
Taxi/Taxi/Extension/ImageExtension.swift
Taxi/Taxi/Extension/ViewExtension.swift
Taxi/Taxi/Presenter/Component/TranparentBackground.swift
Taxi/Taxi/Presenter/Component/UnderlinedTextField.swift
Taxi/Taxi/Presenter/MyPage/ProfileView.swift
Taxi/Taxi/Presenter/SignUp/SignUpCodeView.swift
Taxi/Taxi/Presenter/TaxiPartyTab/TaxiPartyInfoView.swift
Taxi/Taxi/Presenter/TaxiPartyTab/TaxiPartyListView.swift

- 프로필 관리 화면에서 '저장' 버튼 누르면 바로 닫히도록 변경
- 닉네임 첫글자가 영어 소문자면 기본 프로필이 좀 이상한 관계로, 닉네임 변경시 autoCapitalication을 true로 변경
@SH0123 이 제작한 underlinedTextField에도 똑같이 적용 후, 가입코드를 'Popopot'으로 변경
- jpeg 압축률을 0.1로 낮춤
- 프로필 사진이 로딩되기 전의 플레이스홀더를 그냥 회색 원으로 변경
- 정보 확인 뷰가 투명한 풀스크린으로 올라오도록 변경
- 정보 확인 뷰가 풀스크린으로 올라왔을 때, 아래 컨텐츠에 블러를 적용(편법)
- View extension으로 clearBackground 수식어를 만듦
- https://stackoverflow.com/questions/63745084/how-can-i-make-a-background-color-with-opacity-on-a-sheet-view

[Merge] #146 UI 수정사항 반영

---

Taxi/Taxi/Presenter/Component/RoundedButton.swift

- Rounded Button loading state 추가
- [loading 파라미터로 버튼의 loading 상태 및 클릭 여부를 결정한다.](https://github.com/DeveloperAcademy-POSTECH/MC2-Team3-SSAK3/compare/develop...DeveloperAcademy-POSTECH:feature%2F%23150_rounded_button_loading_state?expand=1&title=Design%3A%20Add%20Rounded%20Button%20Loading%20State#diff-f5c67838121be98bf596db02396d12c4571c02ef95821fb55cceb3737f1e73aeR16)

[Merge] #150: Add Rounded Button Loading State

---

Taxi/Taxi/Data/TaxiPartyFirebaseDataSource.swift
Taxi/TaxiTests/AddTaxiPartyUsecaseTest.swift
Taxi/TaxiTests/ChattingUseCaseTest.swift
Taxi/TaxiTests/MyTaxiPartyRepositoryTest.swift
Taxi/TaxiTests/MyTaxiPartyUsecaseTest.swift
Taxi/TaxiTests/TaxiPartyRepositoryTest.swift
Taxi/TaxiTests/UserRepositoryTest.swift

- 택시팟 참가 요청 시 백엔드에서 정원 검사 실행
- 정원이 다 찼을 시 에러반환
- join Taxi Party 로직 firebase functions 으로 변경
- [firebase function 사용 택시팟 참가 로직](https://github.com/DeveloperAcademy-POSTECH/MC2-Team3-SSAK3/compare/develop...DeveloperAcademy-POSTECH:feature%2F%23153_change_join_taxiparty_logic?expand=1&title=153%20%5BFeature%5D%20택시팟%20참가%20인원%20검사%20로직%20추가#diff-569dfccd2c6738bb357709741d40004049d94720bda61946c1ef602c09929224R77)
- join Taxi Party 실패 시 적절한 에러 메시지를 띄워줘야 함
- 브랜치 머지 후 애플리케이션 테스트 부탁드립니다.
- [택시팟 정원 검사 백엔드 코드 작성](https://medium.com/@stephane.giron/firebase-cloud-functions-oncall-returned-before-end-of-the-function-2d898d8ff259)

[Merge] #153: Fix join taxi party logic 

---

Taxi/Taxi.xcodeproj/project.pbxproj
Taxi/Taxi/Data/UserFirebaseDataSource.swift
Taxi/Taxi/Presenter/ViewModel/UserProfileViewModel.swift
Taxi/Taxi/Utility/UserInMemoryCache.swift

- 유저 인메모리 캐시 구현
- 인메모리 캐시를 경유해 User 데이터를 얻어오도록 Data source 로직을 수정
- Data Source 수정에 따라 UserProfileViewModel 함수 호출부 수정 -> 캐시 메모리를 활용하도록
- Dictionary 를 활용한 캐시 구현
- UserProfileVIewModel 함수 호출 수정
- Data Source 데이터 로딩 함수 수정
- 본래 NSCache 를 활용해 캐시 메모리를 구현하려했으나, class 타입에만 사용가능하다는 점 때문에 Dictonary 를 활용해 구현하였다.
- 또한 현재는 메시지 View 마다 각각의 ObservedObject 를 가지고 있어 처음 채팅방 입장 시 똑같은 유저 데이터를 여러 번 로딩한다.
- 이 또한 ChattingViewModel 을 활용해 수정할 예정이다 (UserProfileViewModel 을 사용하지 않도록)

[Merge] #164: Add User In Memory Cache

---

Taxi/Taxi/Presenter/TaxiPartyTab/CalendarModal.swift

tabview 가림 현상의 uitabbar controller를 이용하여 해결
모달이 탭바에 의해 가려지는 현상을 해결하기 위해 ui tab bar controller 이용
toast message state 관련 이슈 해결

Bug: 달력 모달 tabview 가림, toast message 이슈 해결

---

Taxi/Taxi/Presenter/AddTaxiParty/AddTaxiParty.swift

- 택시팟 생성 화면에서 캘린더 선택 시 화면 위 아래로 짤리는 현상 해결 #166 
https://user-images.githubusercontent.com/57793298/175250654-af7a3f7a-441d-4d31-8da9-168ea01b61e7.mp4
- [ScrollView 의 scroll axis 를 빈 배열로 주면, Scroll 이 안되는 ScrollView 를 만들 수 있다.](https://github.com/DeveloperAcademy-POSTECH/MC2-Team3-SSAK3/compare/develop...DeveloperAcademy-POSTECH:bug%2F%23166_layout_issue?expand=1&title=166%20%5BBUG%5D%20택시팟%20생성%20레이아웃%20짤림%20이슈#diff-ca6e65972b124f8cea2e4f909e0392fc8c3d79d83955db07e8acaa47ecb9d711R47)
- VStack 이 차지하는 영역이 너무 길어질 경우, content Layout 의 top anchor 를 고정할 수 있는 다른 방법이 있는지 궁금합니다.
- SwiftUI 의 layout draw principle 에 의해 VStack 을 화면 중앙에 그리는 것으로 보인다. 이로 인해 컨텐츠 영역이 길어질 경우 위 아래로 짤리는 현상이 있는 것 같음

[Merge] #166: Fix AddTaxiParty Layout Issue

---

Taxi/Taxi/Extension/StringExtension.swift
Taxi/Taxi/Presenter/Component/UnderlinedTextField.swift
Taxi/Taxi/Presenter/SignUp/SignUpCodeView.swift
Taxi/Taxi/Presenter/SignUp/SignUpNicknameView.swift

enum takes related value
change overlay at underlinedText to zstack
- FieldState의 case마다 연관값을 주어, 상태에 따른 메시지와 enum의 state에 연관성을 넣어주었습니다.
- overlay로 textfield의 underline으로 만든결과 overlay에 해당하는 부분은 영역으로 잡지 못해 버그가 발생하였고, 이를 개선하기 위해 overlay 대신 zstack 위에 textfield와 rectangle을 쌓았습니다.
연관값을 활용한 부분과 관련하여 리뷰 부탁드립니다.

Refactor: refactor login view

---

Taxi/Taxi/Presenter/TaxiPartyTab/CalendarModal.swift

- 택시팟 없는 날 토스트 메세지 떳다가 0.8초뒤에 사라지도록 구현
- 캘린더 모달 transition
- tabbar custom을 하다보니 모달 transition이 될 때 탭바가 먼저 나타나는 문제 발생 -> dispatchqueue 비동기 시간 지연 적용, 이 방법이 옳을까?

Feat: calendar toast message fade out, modal transition

---

Taxi/Taxi/Presenter/SignIn/SignInEmail.swift
Taxi/Taxi/Presenter/TaxiPartyTab/CalendarModal.swift
Taxi/Taxi/TaxiApp.swift

related to #167
택시팟 있는 날짜 선택 후 확인/취소/모달아닌 부분 터치 다시 달력 모달 켰을 때 확인버튼이 활성화 되어 있던 버그 해결
달력 animation 문제 해결을 위해 lazyVStack 제거

fix: calendar modal 확인 button bug solved

---

Taxi/Taxi/Presenter/MyPage/ProfileView.swift

ProfileView에서 프로필 사진 수정할때, 노란색 버튼 영역을 터치하였을때에도, 프로필 사진 수정이 가능하게끔 Fix
"프로필 사진 변경한 경우", "프로필 사진이 있는 경우", "프로필 사진이 없는 경우"에 모두 적용되도록
ZStack을 Button_label 라벨안에 넣어 Image("profileImage_plus")을 적용하였습니다.
var profileImageEditButton: some View {
Button {
showActionSheet.toggle()
} label: {
ZStack {
if let newImage = selectedImage { // 프로필 사진을 변경한 경우
Image(uiImage: newImage)
.profileCircle(profileSize)
} else if let imageURL = imageContainer { // 프로필 사진이 있는 경우
WebImage(url: URL(string: imageURL))
.profileCircle(profileSize)
} else { // 프로필 사진이 없는 경우
textProfile(profileSize)
}
Image("profileImage_plus")
.resizable()
.frame(width: 48, height: 48)
.opacity(0.8)
}
}
}

Bug: Fix Yellow Plus Edit Button 영역 터치 가능

---

Taxi/Taxi/Presenter/TaxiPartyTab/TaxiPartyInfoView.swift
Taxi/Taxi/Presenter/TaxiPartyTab/TaxiPartyListView.swift

- 정보뷰가 닫혀도 블러가 사라지지 않는 버그를 고쳤습니다.
| 작업 전 | 작업 후 |
| :---: | :---: |
|<img width="250" src="https://user-images.githubusercontent.com/75792767/183079054-64817050-be59-4cbd-97fc-67caf9d12c8b.gif">|<img width="250" src="https://user-images.githubusercontent.com/75792767/183078783-12f63851-e301-4aed-acf6-45ca378d2af0.gif">|
- 블러를 생기게 하는 변수인 showBlur를 변경하는 코드를 모두 제거하고, 정보뷰 풀스크린을 띄우는 변수 showInfoView에 의존하게 하여 버그를 제거했습니다.
```swift
.onChange(of: showInfoView) { _ in
showBlur = showInfoView
}
```
- 이제 더이상 TaxiPartyInfoView에서 showBlur를 다루지 않아, 제거했습니다.

Bug: 정보뷰가 닫혀도 블러가 사라지지 않는 버그

---

Taxi/Taxi/Presenter/TaxiPartyTab/TaxiPartyInfoView.swift
Taxi/Taxi/Presenter/TaxiPartyTab/TaxiPartyListView.swift

- 택시팟 입장시 메인탭 블러가 사라지지 않는 버그를 고쳤습니다.
| 작업 전 | 작업 후 |
| :---: | :---: |
|<img width="250" src="https://user-images.githubusercontent.com/75792767/183096376-2161fb39-14fd-47da-8755-7c47dd1e7dcb.gif">|<img width="250" src="https://user-images.githubusercontent.com/75792767/183096347-700964b7-4f1f-4575-ba19-cd13bf8d89ca.gif">|
- TaxiPartyInfoView에서 showBlur를 다시 주입하고, 입장시 showBlur를 false로 만들도록 했습니다.
- 택시팟 입장도 X버튼이랑 똑같이 dismiss()가 사용돼서 showInfoView가 false가 되고 showBlur도 따라서 false가 돼야할 것 같은데 왜 버그가 생긴 걸까요?

Bug: 택시팟 입장시 메인탭 블러가 사라지지 않는 버그 수정

---

Taxi/Taxi/Data/MockData/MessageMockData.swift
Taxi/Taxi/Data/Repository/MyTaxiPartyFirebaseDataSource.swift
Taxi/Taxi/Data/Repository/TaxiPartyFirebaseDataSource.swift
Taxi/Taxi/Domain/Model/Message.swift
Taxi/Taxi/Extension/DateExtension.swift
Taxi/Taxi/Presenter/Chatting/ChattingViewModel.swift

- [기존엔 12시간제로 timeStamp 가 찍혀서 메시지 순서가 뒤죽박죽이었는데, 24시간제 timeStamp 로 수정해서 이를 해결함](https://github.com/DeveloperAcademy-POSTECH/MC2-Team3-SSAK3/compare/develop...DeveloperAcademy-POSTECH:bug%2F%23212_chatting_message_sort?expand=1&title=212%20%5BBUG%5D%20채팅방%20메시지%20정렬%20순서%20버그&body=기존엔%2012시간제로%20timeStamp%20가%20찍혀서%20메시지%20순서가%20뒤죽박죽이었는데%2C%2024시간제%20timeStamp%20로%20수정해서%20이를%20해결함%0A%0A또한%20Message%20인스턴스의%20initializer%20를%20생성함으로써%2C%20sender%20와%20body%20그리고%20messageType%20만%20지정해주면%20메시지가%20생성하도록%20수정함#diff-39e3e92c61e9a50c4b0278b54476783db24f59635426c674b17e744d4c408a4fR37)
- [또한 Message 인스턴스의 initializer 를 생성함으로써, sender 와 body 그리고 messageType 만 지정해주면 메시지가 생성하도록 수정함](https://github.com/DeveloperAcademy-POSTECH/MC2-Team3-SSAK3/compare/develop...DeveloperAcademy-POSTECH:bug%2F%23212_ch …

[BUG] 채팅방 메시지 정렬 순서 버그

---

Taxi/Taxi/Domain/Model/TaxiParty.swift
Taxi/Taxi/Extension/DateExtension.swift
Taxi/Taxi/Presenter/AddTaxiParty/AddTaxiParty.swift
Taxi/Taxi/Presenter/Chatting/ChatRoomView.swift
Taxi/Taxi/Presenter/Component/PatyListCell.swift
Taxi/Taxi/Presenter/TaxiPartyTab/TaxiPartyInfoView.swift

#226 
- HHmm 형식의 Int로 바꾸는 작업은 3가지 파일에서 진행되기 때문에 global하게 접근할 수 있도록 하였습니다. 하지만 Date extension에 있는 것이 어색하여 Date extension의 dateFormatter들을 formatter 파일로 이동시키는게 어떤가 하는 생각을 해봅니다
- 아래의 코드 부분에서 수식이 들어간 부분을 연산 프로퍼티로 만들었습니다. 문제가 없는지 확인 부탁드립니다. 해당 부분에서 저는 force unwrapping 하는 것을 좋아하지 않아 guard문 처리를 하였고 else 구문에 명확히 오류임을 알 수 있도록 9999라는 값을 넣었습니다. 이와 관련하여 좋은 개선안이 있으면 추천 부탁드립니다
```swift
let taxiParty: TaxiParty = TaxiParty(id: UUID().uuidString, 
departureCode: departure!.toCode(), 
destinationCode: destination!.toCode(), 
meetingDate: startDate!.formattedInt!, 
meetingTime: (startHour! * 100) + startMinute!, 
maxPersonNumber: maxNumber!, 
members: [user.id], 
isClosed: false)
```
```swift
var time: Int {
guard let startHour = startHour, let startMinute = startMinute else { return 9999 }
return …
```

[Refactor] time formatter 사용 방식 리팩토링

---

Taxi/Taxi/Presenter/Component/PatyListCell.swift
Taxi/Taxi/Presenter/MyParty/MyPartyView.swift
Taxi/Taxi/Presenter/TaxiPartyList/TaxiPartyList.swift

- MyPartyView에 ScrollView + LazyVStack으로 구현되어있던 코드를 List로 변경했습니다.
- TaxiPartyList와 동일하게 refreshable을 사용했습니다.
List에 NavigationLink가 들어가면 생기는 chevron/arrow(>)를 없애기 위해서
ZStack안에 PartyListCell과 EmptyView 라벨을 가지는 NavigationLink를 넣고 opacity를 0으로 줬습니다.
```swift
ZStack {
PartyListCell(party: party)
NavigationLink {
ChatRoomView(party: party, user: authentication.userInfo)
.environmentObject(self.viewModel)
} label: {
EmptyView()
}
.opacity(0)
}
```
https://stackoverflow.com/questions/58333499/swiftui-navigationlink-hide-arrow/66262123#66262123

Refactor: Change MyPartyList Vstack to List

---

Taxi/Taxi/Presenter/Chatting/ChatRoomView.swift

- makeMyMessage 메서드와 OpponentMessage 컴포넌트의 Text(message.body)에 `.textSelection(.enabled)` 수식어를 추가하여 메시지 롱탭시 복사 옵션이 나오게 됨
- 위 사진에 있는 계좌번호로 10000원씩 입금부탁요~

[Feature] 메시지 복사 기능

---

Taxi/Taxi.xcodeproj/project.pbxproj
Taxi/Taxi/Presenter/System/RootView.swift

- RootView에서 Splash 뷰가 뜨는 케이스에만 다크 모드 적용하여 상태바 색상을 흰색으로 변경.
- 앱의 Statur Bar Style을 Light Content로 변경하여 앱이 켜질 때 흰색 상태바로 켜지도록 변경(이거 안하면 launchScreen이 뜨는 찰나의 순간에는 상태바가 검정색임)

[Feature] 스플래시 화면에서 상태바를 흰색으로 변경

---

Taxi/Taxi.xcodeproj/project.pbxproj
Taxi/Taxi/Presenter/Component/Header.swift
Taxi/Taxi/Presenter/Component/TabHeader.swift
Taxi/Taxi/Presenter/MyPage/MyPageView.swift
Taxi/Taxi/Presenter/MyParty/MyPartyView.swift
Taxi/Taxi/Presenter/System/MainView.swift
Taxi/Taxi/Presenter/TaxiPartyList/TaxiPartyList.swift

- 상단 여백이 너무 커지는 버그를 수정하고, 디자인 시안대로 19의 간격을 두었습니다.
- 각 탭의 헤더를 컴포넌트로 만들어서 한 번에 관리하도록 했습니다.
- 각 탭의 상단 여백을 잡고 있던 .navigationBarTitleDisplayMode(.inline) 코드를 삭제함.
- MainView의 각 탭의 뷰에 `.navigationBarHidden(true)`를 추가하여 내비게이션바를 숨김.
- TabHeader 컴포넌트에서 필요할때만 버튼에 해당하는 값(아이콘 systemName과 액션 로직)을 받도록 했습니다.

[Bug] 내비게이션바 여백이 너무 크게 보이는 버그 수정

---

Taxi/Taxi/Presenter/MyParty/MyPartyView.swift
Taxi/Taxi/Presenter/TaxiPartyInfo/TaxiPartyInfo.swift

TaxiPartyInfo full screen에 drag gesture를 주어 제스쳐만으로도 해당 스크린을 닫을 수 있도록 하였습니다.
아래의 영상을 보시면 제일 위로 올려도 상단의 safeArea 정도만큼은 다시 full screen이 채워지지 않는 것이 보입니다... 아보의 도움이 필요합니다
https://designcode.io/swiftui-handbook-drag-gesture

Feat: full screen cover with drag gesture

---

Taxi/Taxi/Presenter/Chatting/ChatRoomView.swift

|작업전|작업후|
|:---:|:---:|
|<img width="250" src="https://user-images.githubusercontent.com/75792767/190361159-6af8d22f-70dd-4541-be90-1d0362ba911d.png">|<img width="250" src="https://user-images.githubusercontent.com/75792767/190360010-74d5a81a-0b3f-4476-aaf0-2007cb24bf2d.png">|

[Bug] iOS16에서 채팅 입력 칸 색상이 이상하게 나오는 버그

---

Taxi/Taxi/Presenter/Chatting/ChatRoomInfo.swift

|작업전|작업후|
|:---:|:---:|
|<img width="250" src="https://user-images.githubusercontent.com/75792767/190580184-4407e85f-fc48-4b37-b2a5-ed2ad3881eb3.png">|<img width="250" src="https://user-images.githubusercontent.com/75792767/190579545-2227a125-0899-47d9-b22e-ff408f81c599.png">|
- ForEach에서 non-constant range 오류가 뜨던 것을 `id: \.self`를 추가하여 해결

[Feature] ChatRoomInfo 디자인 시안에 맞게 수정

---

Taxi/Taxi.xcodeproj/project.pbxproj
Taxi/Taxi/Presenter/AddTaxiParty/AddTaxiParty.swift
Taxi/Taxi/Presenter/MyPage/MyPageView.swift
Taxi/Taxi/Presenter/MyParty/MyPartyView.swift
Taxi/Taxi/Presenter/SignIn/SignInViewModel.swift
Taxi/Taxi/Presenter/System/AppState.swift
Taxi/Taxi/Presenter/System/MainView.swift
Taxi/Taxi/Presenter/System/RootView.swift
Taxi/Taxi/Presenter/System/UserInfoState.swift
Taxi/Taxi/Presenter/TaxiPartyInfo/TaxiPartyInfo.swift
Taxi/Taxi/Presenter/TaxiPartyList/ViewModel.swift

- 개인적으로 개발한 **KeychainWrapper Package dependency** 추가 (Password 혹은 accessToken 을 저장하기 위해 만든 패키지)
- Password 를 Keychain 에 추가하도록 변경하고, 이에 따라 autoLogin 또한 Keychain 에 변경하도록 수정했습니다.
- UserInfoState 를 RootView 에서 생성해 주입했을 때 계속해서 새로운 인스턴스가 생성되서, MainView 에서 UserInfoState 를 생성하도록 변경했습니다.
- RootView 의 switch 문에서 environmentObject 로 바로 UserInfoState 를 생성하던 기존 코드가 탭이 변경될 때마다 **UserInfoState 인스턴스를 계속해서 생성시키는 문제**가 있었습니다. (tab 이 변경될 때 body 문도 재실행되고, 이로인해 body 문에서 인스턴스를 계속 생성하게 됨) -> 따라서 UserInfoState 생성에 필요한 userInfo 인스턴스를 MainView 가 생성자로 주입받고, MainView 에서 StateObject 로 생성하도록 변경했습니다. -> **인스턴스가 하나만 생성되는 것을 확인**함
- KeychainWrapper 는 async 와 completion handler API 를 제공하도록 개발했으며, 입맛대로 쓰시면 될 듯 합니다.
- [키체인 참고자료](https://www.raywenderlich.com/9240-keychain-services-api-tutorial-for-passwords-in-swift)
- …

[Merge] #242: Save password to keychain & fix infinity instance init bug

---

Taxi/Taxi/Domain/Model/TaxiParty.swift
Taxi/Taxi/Presenter/Component/PatyListCell.swift
Taxi/Taxi/Presenter/System/MainView.swift
Taxi/Taxi/Presenter/TaxiPartyList/TaxiPartyList.swift

- 셀에 참여중 표시 추가
- 첫번째 탭에서 사용자가 참여한 택시팟 까지 불러 오도록 수정
- 참여중인 셀 클릭시 채팅방으로 이동
사용자 본인이 참여한 택시팟 까지 불러 오도록 수정할 때
MainView 파일에서 viewmodel 선언시 exclude 파라미터를 넣지 않는 것으로 했는데
ViewModel 파일에 있는 exclude 관련 코드도 변경하는 것이 좋을까요?
```swift
self._taxiPartyViewModel = StateObject(wrappedValue: TaxiPartyList.ViewModel(addTaxiPartyDelegate: listViewModel, joinTaxiPartyDelegate: listViewModel))
```
[링크](https://github.com/DeveloperAcademy-POSTECH/MC2-Team3-SSAK3/compare/feature/%23261_PartyListCell_Participate?expand=1#diff-9d4391c2e3a411f0c170ea636d9fa8d727c2edd228c8f6110b368a06d24d7a1cL45)

[Feature] 파티 리스트 셀 참여중 표시 추가

---

Taxi/Taxi/Presenter/SignIn/SignHome.swift
Taxi/Taxi/Presenter/SignIn/SignIn.swift
Taxi/Taxi/Presenter/SignUp/SignUpComplete.swift
Taxi/Taxi/Presenter/SignUp/SignUpEmail.swift
Taxi/Taxi/Presenter/SignUp/SignUpNickname.swift
Taxi/Taxi/Presenter/SignUp/SignUpPassword.swift

- 회원가입이 끝난 완료 화면에서 '시작하기' 버튼을 누르면 바로 로그인 화면이 뜨게 만들었습니다.
- 그리고 해당 로그인 화면에서는 회원가입 플로우에서 입력한(SignUpViewModel에 있는) email과 password이 바로 입력되어 있도록 했습니다.
- 이 방식을 선택한 이유는 인증이 완료됐는지도 모르는 상황에서 이메일과 비밀번호를 UserDefaults와 KeyChain에 저장하는건 아니라고 생각했기 때문입니다.
- SignUpComplete에서 SignInViewModel을 StateObject로 생성 후 SignIn 뷰에 전달
- SignIn의 onAppear에서 SignUpViewModel에 저장되어 있는 email과 password를 SignInViewModel의 email과 password에 전달

[Feat] 회원가입하고 바로 로그인되게
